#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'almostSorted' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def almostSorted(arr):
    # Write your code here
    l=sorted(arr)
    m=-1
    n=-1
    for i in range(len(arr)):
        if arr[i]!=l[i]:
            if m==-1:
                m=i
            else:
                n=i
    arr[m],arr[n]=arr[n],arr[m]
    if arr==l:
        print("yes")
        print("swap",m+1,n+1)
        return
    arr[m],arr[n]=arr[n],arr[m]
    i,j=m,n
    while m<=n:
        arr[m],arr[n]=arr[n],arr[m]
        m+=1
        n-=1
    if arr==l:
        print("yes")
        print("reverse",i+1,j+1)
        return
    print("no")

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    almostSorted(arr)
